create database future2016;
use future2016;


-- 成交信息_加密.csv
create table chengjiao (
CAPITAL_ACCOUNT_NEW char(12),
TRADEDATE date,
DONE_NO int,
MARKET_CODE char(1),
SEAT_CODE char(6),
VARI_CODE char(2),
DELIV_DATE int,
DONE_PRICE double,
DONE_QTY int,
CURRENCY_CODE char(1),
BS_FLAG char(1),
SH_FLAG char(1),
EO_FLAG char(1),
COMMISSION double,
MARKET_COMMISSION double,
OTHER_FEE double,
MARKET_OTHER_FEE double,
ADD_FEE1 double,
ADD_FEE2 double,
COMMISSION_RATE double,
COMMISSION_AMOUNT double,
MARKET_COMMISSION_RATE double,
MARKET_COMMISSION_AMOUNT double,
ADD_FEE1_RATE double,
ADD_FEE1_AMOUNT double,
ADD_FEE2_RATE double,
ADD_FEE2_AMOUNT double,
OPERATOR_NO char(12),
MARKET_DONE_NO char(12),
SYS_NO int,
ENTRUST_WAY char(1),
DONE_TIME time,
SPECIFY_PRICE double,
HANDS int,
FEE_FLAG int,
FORCE_OFFSET char(1),
QTY int,
ORIGIN_EXCH_COMMI double,
DONE_TIME1 time,
ORDER_WAY char(1),
O_MARKET_COMMISSION_RATE double,
O_MARKET_COMMISSION_AMOUNT double,
ORDER_ID char(16),
MARKET_SEAT_CODE char(10)
);


-- 持仓信息_加密.csv
create table chicang (
CAPITAL_ACCOUNT_NEW char(12),
TRADEDATE date,
OPEN_DATE date,
DONE_NO int,
MARKET_CODE char(1),
SEAT_CODE char(6),
VARI_CODE char(2),
DELIV_DATE int,
OPEN_PRICE double,
OPEN_HAND int,
CURRENCY_CODE char(1),
BS_FLAG char(1),
SH_FLAG char(1),
YEST_SETTLE_PRICE double,
TODAY_SETTLE_PRICE double,
MARGIN double,
MARKET_MARGIN double,
HOLD_PROFIT_F double,
HOLD_PROFIT_D double,
HANDS int,
ZR_FLAG char(1),
DC_FLAG char(1),
MARKET_DONE_NO int,
QTY int
);


-- 平仓信息_加密.csv
create table pingcang (
CAPITAL_ACCOUNT_NEW char(12),
TRADEDATE date,
DONE_NO int,
OPEN_DATE date,
OPEN_DONE_NO int,
MARKET_CODE char(1),
SEAT_CODE char(6),
VARI_CODE char(2),
DELIV_DATE int,
CURRENCY_CODE char(1),
OFFSET_HAND int,
OFFSET_PRICE double,
OPEN_PRICE double,
BS_FLAG char(1),
SH_FLAG char(1),
LAST_SETTLE_PRICE double,
DROP_PROFIT_F double,
DROP_PROFIT_D double,
HANDS int,
OFFSET_TYPE char(1),
ZR_FLAG char(1),
DC_FLAG char(1)
);


-- 委托信息_加密.csv
create table weituo (
CAPITAL_ACCOUNT_NEW char(12),
TRADEDATE date,
ENTRUST_NO int,
OPERATOR_NO char(12),
MARKET_CODE char(1),
STOCKHOLDER int,
VARI_CODE char(2),
DELIV_DATE char(4),
BS_FLAG char(1),
SH_FLAG char(1),
EO_FLAG char(1),
SYS_NO int,
SEAT_CODE char(5),
ENTRUST_QTY int,
ENTRUST_PRICE double,
REMAIN_QTY int,
DONE_QTY int,
DONE_PRICE double,
FRZN_MARGIN double,
FRZN_COMMI double,
ENTRUST_TIME time,
ORDER_TIME time,
CANCEL_TIME time,
CANCEL_OPER char(12),
ENTRUST_TYPE char(1),
ENTRUST_STATUS char(1),
CMD_NO int,
ENTRUST_WAY char(1),
EN_OPER_TYPE char(1),
DEAL_INF char(1),
REMARK char(1),
CURRENCY_CODE char(1),
SEND_TO_RPT_FLAG char(1),
UPDATE_BATCH char(1),
FORCE_OFFSET char(1),
ENTRUST_SEAT_OPER char(1),
LOCAL_FLAG char(1),
BRANCH_CODE char(4)
);


-- 账户信息_加密.csv
create table zhanghu (
CAPITAL_ACCOUNT_NEW char(12),
BRANCH_CODE char(4),
CLIENT_NAME char(6),
CLIENT_FULL_NAME char(6),
CUST_CLASS char(10),
STATUS char(1),
ACCOUNT_HEAD_TYPE char(1),
CERTIFICATE_TYPE char(1),
CERTIFICATE_ID char(18),
SHAREMONEY char(1),
OPEN_DATE date,
CLOSE_DATE date,
IF_HAND char(1),
IF_MARGIN char(1),
IF_CODE char(1),
IF_RET char(1),
IF_AUTH char(1),
IF_PROP char(1),
NOTE varchar(70),
OPERATOR_NO char(10),
OPER_DATE date,
OPER_TIME time,
OPEN_OPERATOR_NO char(10),
CLOSE_OPERATOR_NO char(10),
CREDIT int,
CERT_END_DATE date,
SLEEP_STATUS char(1)
);


-- 资金信息_加密.csv
create table zijin (
CAPITAL_ACCOUNT_NEW char(12),
TRADEDATE date,
CURRENCY_CODE char(1),
LAST_REMAIN double,
IN_MONEY double,
OUT_MONEY double,
COMMISSION double,
MARKET_COMMISSION double,
ADD_FEE1 double,
ADD_FEE2 double,
HOLD_PROFIT_D double,
DROP_PROFIT_D double,
DROP_PROFIT_F double,
OTHER_FEE double,
MARKET_OTHER_FEE double,
TODAY_REMAIN double,
HOLD_PROFIT_F double,
WAY_MONEY double,
UNDELIV_PROFIT double,
END_RIGHTS double,
MARGIN double,
BASE_MARGIN double,
AVAIL_FUND double,
PLEDGE_AMOUNT double,
MARKET_MARGIN double,
RISK_LEVEL char(1),
RISK_DEGREE1 double,
RISK_DEGREE2 double,
ADD_MARGIN double,
DELIV_PROFIT double,
AGIO_MARGIN double,
DELIV_COMMISSION double,
DELIV_MARKET_COMMISSION double,
DELIV_MARGIN double,
DELIV_MARKET_MARGIN double,
CLEAR_MONEY double,
REMAIN_COMMISSION double,
PROFIT double,
CLEAR_PROFIT double
);

